/* soapClient.cpp
   Generated by gSOAP 2.8.92 for ws-inspire-wfs2.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.92 2020-05-03 21:39:58 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002ecreateStoredQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__CreateStoredQueryType *wfs__CreateStoredQuery, wfs__CreateStoredQueryResponseType &wfs__CreateStoredQueryResponse)
{	if (soap_send___f2i_plu__wfs_x002ecreateStoredQuery(soap, soap_endpoint, soap_action, wfs__CreateStoredQuery) || soap_recv___f2i_plu__wfs_x002ecreateStoredQuery(soap, wfs__CreateStoredQueryResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002ecreateStoredQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__CreateStoredQueryType *wfs__CreateStoredQuery)
{	struct __f2i_plu__wfs_x002ecreateStoredQuery soap_tmp___f2i_plu__wfs_x002ecreateStoredQuery;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:CreateStoredQueryRequest";
	soap_tmp___f2i_plu__wfs_x002ecreateStoredQuery.wfs__CreateStoredQuery = wfs__CreateStoredQuery;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002ecreateStoredQuery(soap, &soap_tmp___f2i_plu__wfs_x002ecreateStoredQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002ecreateStoredQuery(soap, &soap_tmp___f2i_plu__wfs_x002ecreateStoredQuery, "-f2i-plu:wfs.createStoredQuery", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002ecreateStoredQuery(soap, &soap_tmp___f2i_plu__wfs_x002ecreateStoredQuery, "-f2i-plu:wfs.createStoredQuery", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002ecreateStoredQuery(struct soap *soap, wfs__CreateStoredQueryResponseType &wfs__CreateStoredQueryResponse)
{
	struct __f2i_plu__wfs_x002ecreateStoredQueryResponse *soap_tmp___f2i_plu__wfs_x002ecreateStoredQueryResponse;
	wfs__CreateStoredQueryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___f2i_plu__wfs_x002ecreateStoredQueryResponse = soap_get___f2i_plu__wfs_x002ecreateStoredQueryResponse(soap, NULL, "-f2i-plu:wfs.createStoredQueryResponse", NULL);
	if (!soap_tmp___f2i_plu__wfs_x002ecreateStoredQueryResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	wfs__CreateStoredQueryResponse = soap_tmp___f2i_plu__wfs_x002ecreateStoredQueryResponse->wfs__CreateStoredQueryResponse;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002edescribeFeatureType(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__DescribeFeatureTypeType *wfs__DescribeFeatureType, util__DescribeFeatureTypeResponseType &util__DescribeFeatureTypeResponse)
{	if (soap_send___f2i_plu__wfs_x002edescribeFeatureType(soap, soap_endpoint, soap_action, wfs__DescribeFeatureType) || soap_recv___f2i_plu__wfs_x002edescribeFeatureType(soap, util__DescribeFeatureTypeResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002edescribeFeatureType(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__DescribeFeatureTypeType *wfs__DescribeFeatureType)
{	struct __f2i_plu__wfs_x002edescribeFeatureType soap_tmp___f2i_plu__wfs_x002edescribeFeatureType;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:DescribeFeatureTypeRequest";
	soap_tmp___f2i_plu__wfs_x002edescribeFeatureType.wfs__DescribeFeatureType = wfs__DescribeFeatureType;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002edescribeFeatureType(soap, &soap_tmp___f2i_plu__wfs_x002edescribeFeatureType);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002edescribeFeatureType(soap, &soap_tmp___f2i_plu__wfs_x002edescribeFeatureType, "-f2i-plu:wfs.describeFeatureType", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002edescribeFeatureType(soap, &soap_tmp___f2i_plu__wfs_x002edescribeFeatureType, "-f2i-plu:wfs.describeFeatureType", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002edescribeFeatureType(struct soap *soap, util__DescribeFeatureTypeResponseType &util__DescribeFeatureTypeResponse)
{
	util__DescribeFeatureTypeResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	util__DescribeFeatureTypeResponse.soap_get(soap, "util:DescribeFeatureTypeResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002egetFeature(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__GetFeatureType *wfs__GetFeature, wfs__FeatureCollectionType &wfs__FeatureCollection)
{	if (soap_send___f2i_plu__wfs_x002egetFeature(soap, soap_endpoint, soap_action, wfs__GetFeature) || soap_recv___f2i_plu__wfs_x002egetFeature(soap, wfs__FeatureCollection))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002egetFeature(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__GetFeatureType *wfs__GetFeature)
{	struct __f2i_plu__wfs_x002egetFeature soap_tmp___f2i_plu__wfs_x002egetFeature;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:GetFeatureRequest";
	soap_tmp___f2i_plu__wfs_x002egetFeature.wfs__GetFeature = wfs__GetFeature;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002egetFeature(soap, &soap_tmp___f2i_plu__wfs_x002egetFeature);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002egetFeature(soap, &soap_tmp___f2i_plu__wfs_x002egetFeature, "-f2i-plu:wfs.getFeature", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002egetFeature(soap, &soap_tmp___f2i_plu__wfs_x002egetFeature, "-f2i-plu:wfs.getFeature", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002egetFeature(struct soap *soap, wfs__FeatureCollectionType &wfs__FeatureCollection)
{
	wfs__FeatureCollection.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__FeatureCollection.soap_get(soap, "wfs:FeatureCollection", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002edescribeStoredQueries(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__DescribeStoredQueriesType *wfs__DescribeStoredQueries, wfs__DescribeStoredQueriesResponseType &wfs__DescribeStoredQueriesResponse)
{	if (soap_send___f2i_plu__wfs_x002edescribeStoredQueries(soap, soap_endpoint, soap_action, wfs__DescribeStoredQueries) || soap_recv___f2i_plu__wfs_x002edescribeStoredQueries(soap, wfs__DescribeStoredQueriesResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002edescribeStoredQueries(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__DescribeStoredQueriesType *wfs__DescribeStoredQueries)
{	struct __f2i_plu__wfs_x002edescribeStoredQueries soap_tmp___f2i_plu__wfs_x002edescribeStoredQueries;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:DescribeStoredQueriesRequest";
	soap_tmp___f2i_plu__wfs_x002edescribeStoredQueries.wfs__DescribeStoredQueries = wfs__DescribeStoredQueries;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002edescribeStoredQueries(soap, &soap_tmp___f2i_plu__wfs_x002edescribeStoredQueries);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002edescribeStoredQueries(soap, &soap_tmp___f2i_plu__wfs_x002edescribeStoredQueries, "-f2i-plu:wfs.describeStoredQueries", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002edescribeStoredQueries(soap, &soap_tmp___f2i_plu__wfs_x002edescribeStoredQueries, "-f2i-plu:wfs.describeStoredQueries", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002edescribeStoredQueries(struct soap *soap, wfs__DescribeStoredQueriesResponseType &wfs__DescribeStoredQueriesResponse)
{
	wfs__DescribeStoredQueriesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__DescribeStoredQueriesResponse.soap_get(soap, "wfs:DescribeStoredQueriesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002elistStoredQueries(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__ListStoredQueriesType *wfs__ListStoredQueries, wfs__ListStoredQueriesResponseType &wfs__ListStoredQueriesResponse)
{	if (soap_send___f2i_plu__wfs_x002elistStoredQueries(soap, soap_endpoint, soap_action, wfs__ListStoredQueries) || soap_recv___f2i_plu__wfs_x002elistStoredQueries(soap, wfs__ListStoredQueriesResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002elistStoredQueries(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__ListStoredQueriesType *wfs__ListStoredQueries)
{	struct __f2i_plu__wfs_x002elistStoredQueries soap_tmp___f2i_plu__wfs_x002elistStoredQueries;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:ListStoredQueriesRequest";
	soap_tmp___f2i_plu__wfs_x002elistStoredQueries.wfs__ListStoredQueries = wfs__ListStoredQueries;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002elistStoredQueries(soap, &soap_tmp___f2i_plu__wfs_x002elistStoredQueries);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002elistStoredQueries(soap, &soap_tmp___f2i_plu__wfs_x002elistStoredQueries, "-f2i-plu:wfs.listStoredQueries", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002elistStoredQueries(soap, &soap_tmp___f2i_plu__wfs_x002elistStoredQueries, "-f2i-plu:wfs.listStoredQueries", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002elistStoredQueries(struct soap *soap, wfs__ListStoredQueriesResponseType &wfs__ListStoredQueriesResponse)
{
	wfs__ListStoredQueriesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__ListStoredQueriesResponse.soap_get(soap, "wfs:ListStoredQueriesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002edropStoredQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, _wfs__DropStoredQuery *wfs__DropStoredQuery, wfs__ExecutionStatusType &wfs__DropStoredQueryResponse)
{	if (soap_send___f2i_plu__wfs_x002edropStoredQuery(soap, soap_endpoint, soap_action, wfs__DropStoredQuery) || soap_recv___f2i_plu__wfs_x002edropStoredQuery(soap, wfs__DropStoredQueryResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002edropStoredQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, _wfs__DropStoredQuery *wfs__DropStoredQuery)
{	struct __f2i_plu__wfs_x002edropStoredQuery soap_tmp___f2i_plu__wfs_x002edropStoredQuery;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:DropStoredQueryRequest";
	soap_tmp___f2i_plu__wfs_x002edropStoredQuery.wfs__DropStoredQuery = wfs__DropStoredQuery;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002edropStoredQuery(soap, &soap_tmp___f2i_plu__wfs_x002edropStoredQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002edropStoredQuery(soap, &soap_tmp___f2i_plu__wfs_x002edropStoredQuery, "-f2i-plu:wfs.dropStoredQuery", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002edropStoredQuery(soap, &soap_tmp___f2i_plu__wfs_x002edropStoredQuery, "-f2i-plu:wfs.dropStoredQuery", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002edropStoredQuery(struct soap *soap, wfs__ExecutionStatusType &wfs__DropStoredQueryResponse)
{
	struct __f2i_plu__wfs_x002edropStoredQueryResponse *soap_tmp___f2i_plu__wfs_x002edropStoredQueryResponse;
	wfs__DropStoredQueryResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___f2i_plu__wfs_x002edropStoredQueryResponse = soap_get___f2i_plu__wfs_x002edropStoredQueryResponse(soap, NULL, "-f2i-plu:wfs.dropStoredQueryResponse", NULL);
	if (!soap_tmp___f2i_plu__wfs_x002edropStoredQueryResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	wfs__DropStoredQueryResponse = soap_tmp___f2i_plu__wfs_x002edropStoredQueryResponse->wfs__DropStoredQueryResponse;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002egetCapabilities(struct soap *soap, const char *soap_endpoint, const char *soap_action, ows__GetCapabilitiesType *ows__GetCapabilities, wfs__WFS_x005fCapabilitiesType &wfs__WFS_x005fCapabilities)
{	if (soap_send___f2i_plu__wfs_x002egetCapabilities(soap, soap_endpoint, soap_action, ows__GetCapabilities) || soap_recv___f2i_plu__wfs_x002egetCapabilities(soap, wfs__WFS_x005fCapabilities))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002egetCapabilities(struct soap *soap, const char *soap_endpoint, const char *soap_action, ows__GetCapabilitiesType *ows__GetCapabilities)
{	struct __f2i_plu__wfs_x002egetCapabilities soap_tmp___f2i_plu__wfs_x002egetCapabilities;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:GetCapabilitiesRequest";
	soap_tmp___f2i_plu__wfs_x002egetCapabilities.ows__GetCapabilities = ows__GetCapabilities;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002egetCapabilities(soap, &soap_tmp___f2i_plu__wfs_x002egetCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002egetCapabilities(soap, &soap_tmp___f2i_plu__wfs_x002egetCapabilities, "-f2i-plu:wfs.getCapabilities", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002egetCapabilities(soap, &soap_tmp___f2i_plu__wfs_x002egetCapabilities, "-f2i-plu:wfs.getCapabilities", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002egetCapabilities(struct soap *soap, wfs__WFS_x005fCapabilitiesType &wfs__WFS_x005fCapabilities)
{
	wfs__WFS_x005fCapabilities.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__WFS_x005fCapabilities.soap_get(soap, "wfs:WFS_Capabilities", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002egetFeatureWithLock(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__GetFeatureWithLockType *wfs__GetFeatureWithLock, wfs__FeatureCollectionType &wfs__FeatureCollection)
{	if (soap_send___f2i_plu__wfs_x002egetFeatureWithLock(soap, soap_endpoint, soap_action, wfs__GetFeatureWithLock) || soap_recv___f2i_plu__wfs_x002egetFeatureWithLock(soap, wfs__FeatureCollection))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002egetFeatureWithLock(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__GetFeatureWithLockType *wfs__GetFeatureWithLock)
{	struct __f2i_plu__wfs_x002egetFeatureWithLock soap_tmp___f2i_plu__wfs_x002egetFeatureWithLock;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:GetFeatureWithLockRequest";
	soap_tmp___f2i_plu__wfs_x002egetFeatureWithLock.wfs__GetFeatureWithLock = wfs__GetFeatureWithLock;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002egetFeatureWithLock(soap, &soap_tmp___f2i_plu__wfs_x002egetFeatureWithLock);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002egetFeatureWithLock(soap, &soap_tmp___f2i_plu__wfs_x002egetFeatureWithLock, "-f2i-plu:wfs.getFeatureWithLock", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002egetFeatureWithLock(soap, &soap_tmp___f2i_plu__wfs_x002egetFeatureWithLock, "-f2i-plu:wfs.getFeatureWithLock", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002egetFeatureWithLock(struct soap *soap, wfs__FeatureCollectionType &wfs__FeatureCollection)
{
	wfs__FeatureCollection.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__FeatureCollection.soap_get(soap, "wfs:FeatureCollection", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002egetPropertyValue(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__GetPropertyValueType *wfs__GetPropertyValue, wfs__ValueCollectionType &wfs__ValueCollection)
{	if (soap_send___f2i_plu__wfs_x002egetPropertyValue(soap, soap_endpoint, soap_action, wfs__GetPropertyValue) || soap_recv___f2i_plu__wfs_x002egetPropertyValue(soap, wfs__ValueCollection))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002egetPropertyValue(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__GetPropertyValueType *wfs__GetPropertyValue)
{	struct __f2i_plu__wfs_x002egetPropertyValue soap_tmp___f2i_plu__wfs_x002egetPropertyValue;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:GetPropertyValueRequest";
	soap_tmp___f2i_plu__wfs_x002egetPropertyValue.wfs__GetPropertyValue = wfs__GetPropertyValue;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002egetPropertyValue(soap, &soap_tmp___f2i_plu__wfs_x002egetPropertyValue);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002egetPropertyValue(soap, &soap_tmp___f2i_plu__wfs_x002egetPropertyValue, "-f2i-plu:wfs.getPropertyValue", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002egetPropertyValue(soap, &soap_tmp___f2i_plu__wfs_x002egetPropertyValue, "-f2i-plu:wfs.getPropertyValue", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002egetPropertyValue(struct soap *soap, wfs__ValueCollectionType &wfs__ValueCollection)
{
	wfs__ValueCollection.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__ValueCollection.soap_get(soap, "wfs:ValueCollection", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002elockFeature(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__LockFeatureType *wfs__LockFeature, wfs__LockFeatureResponseType &wfs__LockFeatureResponse)
{	if (soap_send___f2i_plu__wfs_x002elockFeature(soap, soap_endpoint, soap_action, wfs__LockFeature) || soap_recv___f2i_plu__wfs_x002elockFeature(soap, wfs__LockFeatureResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002elockFeature(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__LockFeatureType *wfs__LockFeature)
{	struct __f2i_plu__wfs_x002elockFeature soap_tmp___f2i_plu__wfs_x002elockFeature;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:LockFeatureRequest";
	soap_tmp___f2i_plu__wfs_x002elockFeature.wfs__LockFeature = wfs__LockFeature;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002elockFeature(soap, &soap_tmp___f2i_plu__wfs_x002elockFeature);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002elockFeature(soap, &soap_tmp___f2i_plu__wfs_x002elockFeature, "-f2i-plu:wfs.lockFeature", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002elockFeature(soap, &soap_tmp___f2i_plu__wfs_x002elockFeature, "-f2i-plu:wfs.lockFeature", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002elockFeature(struct soap *soap, wfs__LockFeatureResponseType &wfs__LockFeatureResponse)
{
	wfs__LockFeatureResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__LockFeatureResponse.soap_get(soap, "wfs:LockFeatureResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___f2i_plu__wfs_x002etransaction(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__TransactionType *wfs__Transaction, wfs__TransactionResponseType &wfs__TransactionResponse)
{	if (soap_send___f2i_plu__wfs_x002etransaction(soap, soap_endpoint, soap_action, wfs__Transaction) || soap_recv___f2i_plu__wfs_x002etransaction(soap, wfs__TransactionResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___f2i_plu__wfs_x002etransaction(struct soap *soap, const char *soap_endpoint, const char *soap_action, wfs__TransactionType *wfs__Transaction)
{	struct __f2i_plu__wfs_x002etransaction soap_tmp___f2i_plu__wfs_x002etransaction;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://plu.fit2inspire.eu/";
	if (soap_action == NULL)
		soap_action = "http://plu.fit2inspire.eu//wfs/wfs-req:TransactionRequest";
	soap_tmp___f2i_plu__wfs_x002etransaction.wfs__Transaction = wfs__Transaction;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___f2i_plu__wfs_x002etransaction(soap, &soap_tmp___f2i_plu__wfs_x002etransaction);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___f2i_plu__wfs_x002etransaction(soap, &soap_tmp___f2i_plu__wfs_x002etransaction, "-f2i-plu:wfs.transaction", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___f2i_plu__wfs_x002etransaction(soap, &soap_tmp___f2i_plu__wfs_x002etransaction, "-f2i-plu:wfs.transaction", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___f2i_plu__wfs_x002etransaction(struct soap *soap, wfs__TransactionResponseType &wfs__TransactionResponse)
{
	wfs__TransactionResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	wfs__TransactionResponse.soap_get(soap, "wfs:TransactionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
